### ISSUE TITLE
"grad_norm" and "grad_max"

### ISSUE THREAD

**Issue by xk-y** [DENG-MIT/StiffNeuralODE#1]
Hi! I was wondering if the `grad_norm` and `grad_max` could help mitigate gradient pathologies. In POLLU the gradients are divided by their norm and times grad_max, but in ROBER it is not the case. Thanks!
https://github.com/DENG-MIT/StiffNeuralODE/blob/51aeb3bf9c7840d4d97a4d87de094722cffea34b/ROBER/ROBER.jl#L134-L137
https://github.com/DENG-MIT/StiffNeuralODE/blob/51aeb3bf9c7840d4d97a4d87de094722cffea34b/POLLU/POLLU.jl#L217-L221

**Comment by jiweiqi** [comment]
hi @xk-y , the LN219 in POLLU.jl is essentially commonly used grad clipping, that may improve the training. I don't remember whether it has a substantial effect in this case. You may have a quick try to confirm it.

**Comment by xk-y** [comment]
Sorry for the late reply. Thanks! This makes a lot of sense.
